xmlblaster:
  mom:
    port:                8080
    host:                82.103.128.69
    publish_user:        your_user_here
    publish_password:    your_password_here 
  subscriber:
    port:                8081
    host:                your_ip_here 
    public_host:
    public_port:
    topics:              SSO
    subscriber_user:     saas.hosts.nubola-saas.com
    subscriber_password: your_password_here

